### ISSUE TITLE
README links are broken

### ISSUE THREAD

**Issue by granmoe** [elm-lang/browser#2]
staticPage — learn how to show things with elm-lang/html
sandbox — react to user input, like buttons and checkboxes
embed — talk to the outside world, like HTTP and JS interop
fullscreen — create single-page apps

^ These don't work. Are they supposed to be links?

**Comment by andys8** [comment]
I guess they should point to the related code. I made a PR in case this is how it should be.

**Comment by jinjor** [comment]
Did you see #1 ?

**Comment by andys8** [comment]
@jinjor Thanks for the hint
